[general]
base_dir = "/home/runner/dobby/"

[[group]]
path = "files"
recursive = true

	[[group.rule]]
	includes = [".py",".pyc",".html",".txt",".css",".md",".js",".htm",".mhtm",".mhtml",".c",".h",".cpp",".jar",".java"]
	action = "move"
	move_to = "$bp/code_and_text"

	[[group.rule]]
	includes = ["dobby","harry","hagrid","potter","kreacher","voldemort","weasly","wizard","ron","hermione","dumbledore"]
	action = "move"
	move_to = "$bp/harry"

	[[group.rule]]
	includes = ["grace","vanderwaal","ukelele"]
	action = "move"
	move_to = "$bp/ukulele"

	[[group.rule]]
	regex = '[Ss]creenshot.(\d{4}).(\d{2}).(\d{2})(.*?)^'
	action = "move"
	move_to = "$bp/screenshots/$1/_{['January','February','March','April','May','June','July','August','September','October','November','December'][int('$2')]}/$3/$4"

	[[group.rule]]
	regex = '[Uu]ntitled'
	action = "move"
	move_to = "$bp/untitled/$name"

	[[group.rule]]
	includes = [".jpg",".jpeg",".jpe",".jif",".jfif",".jfi",".png",".gif",".webp",".tif",".tiff",".psd",".raw",".arw",".cr2",".nrw",".k25",".bmp",".dib",".heif",".heic",".ind",".indd",".indt",".jp2",".j2k",".jpf",".jpx",".jpm",".mj2",".svg",".svgz",".ai",".eps",".cur"]
	action = "move"
	move_to = "$bp/images"

	[[group.rule]]
	includes = [".3gp",".aa",".aac",".aax",".act",".aiff",".alac",".amr",".ape",".au",".awb",".dct",".dss",".dvf",".flac",".gsm",".iklax",".ivs",".m4a",".m4b",".m4p",".mmf",".mp3",".mpc",".msv",".nmf",".ogg",".oga",".mogg",".opus",".ra",".rm",".raw",".rf64",".sln",".tta",".voc",".vox",".wav",".wma",".wv",".webm",".8svx",".cda"]
	action = "move"
	move_to = "$bp/audio"

	[[group.rule]]
	includes = [".webm",".mkv",".flv",".flv",".vob",".ogv",".ogg",".drc",".gifv",".mng",".avi",".MTS",".M2TS",".TS",".mov",".qt",".wmv",".yuv",".rm",".rmvb",".viv",".asf",".amv",".mp4",".m4v",".mpg",".mp2",".mpeg",".mpe",".mpv",".mpg",".mpeg",".m2v",".m4v",".svi",".3gp",".3g2",".mxf",".roq",".nsv",".flv",".f4v",".f4p",".f4a",".f4b"]
	action = "move"
	move_to = "$bp/videos"
		
	[[group.rule]]
	includes = [".7z",".s7z",".ace",".afa",".alz",".apk",".arc",".ark",".arc",".cdx",".arj",".b1",".b6z",".ba",".bh",".cab",".car",".cfs",".cpt",".dar",".dd",".dgc",".dmg",".ear",".gca",".ha",".hki",".ice",".jar",".kgb",".lzh",".lha",".lzx",".pak",".partimg",".paq6",".paq7",".paq8",".pea",".pim",".pit",".qda",".rar",".rk",".sda",".sea",".sen",".sfx",".shk",".sit",".sitx",".sqx",".tar.gz",".tgz",".tar.Z",".tar.bz2",".tbz2",".tar.lz",".tlz.",".tar.xz",".txz",".uc",".uc0",".uc2",".ucn",".ur2",".ue2",".uca",".uha",".war",".wim",".xar",".xp3",".yz1",".zip",".zipx",".zoo",".zpaq",".zz",".bz2",".F",".gz",".lz",".lz4",".lzma",".lzo",".rz",".sfark",".sz",".?Q?",".?Z?",".xz",".z",".Z",".zst",".??_",".a",".ar",".cpio",".shar",".LBR",".iso",".lbr",".mar",".sbx",".tar"]
	action = "move"
	move_to = "$bp/archives"

	[[group.rule]]
	includes = [".xls",".ppt",".pdf",".docx",".doc",".rtf"]
	action = "move"
	move_to = "$bp/documents"

	[[group.rule]]
	includes = [".stl",".obj"]
	action = "move"
	move_to = "$bp/3d"

	[group.other]
	action = "move"
	move_to = "$bp/other"